name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Pull dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
